from django.conf.urls import patterns, url

from api_docs.views import IPythonNotebookPage


urlpatterns = patterns(
    '',
    url("/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='cron_jobs'),
        name='ipython-notebook-cron_jobs'),
    url("pytables/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='pytables'),
        name='ipython-notebook-pytables'),
    url("excel-python-and-plotly/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='excel_python_and_plotly'),
        name='ipython-notebook-excel_python_and_plotly'),
    url("mne-tutorial/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='mne-tutorial'),
        name='ipython-notebook-mne-tutorial'),
    url("bicycle-control-design/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='bicycle_control'),
        name='ipython-notebook-bicycle_control'),
    url("computational-bayesian-analysis/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='montecarlo'),
        name='ipython-notebook-montecarlo'),
    url("bioinformatics/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='bioinformatics'),
        name='ipython-notebook-bioinformatics'),
    url("baltimore-vital-signs/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='baltimore'),
        name='ipython-notebook-baltimore'),
    url("aircraft-pitch-analysis-matlab-plotly/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='aircraft_pitch'),
        name='ipython-notebook-aircraft_pitch'),
    url("cufflinks/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='cufflinks'),
        name='ipython-notebook-cufflinks'),
    url("survival-analysis-r-vs-python/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='survival_analysis'),
        name='ipython-notebook-survival_analysis'),
    url("amazon-redshift/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='redshift'),
        name='ipython-notebook-redshift'),
    url("apache-spark/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='apachespark'),
        name='ipython-notebook-apachespark'),
    url("principal-component-analysis/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='principal_component_analysis'),
        name='ipython-notebook-principal_component_analysis'),
    url("big-data-analytics-with-pandas-and-sqlite/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='sqlite'),
        name='ipython-notebook-sqlite'),
    url("ukelectionbbg/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='ukelectionbbg'),
        name='ipython-notebook-ukelectionbbg'),
    url("salesforce/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='salesforce'),
        name='ipython-notebook-salesforce'),
    url("graph-gmail-inbox-data/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='gmail'),
        name='ipython-notebook-gmail'),
    url("markowitz-portfolio-optimization/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='markowitz'),
        name='ipython-notebook-markowitz'),
    url("cartodb/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='cartodb'),
        name='ipython-notebook-cartodb'),
    url("network-graphs/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='networkx'),
        name='ipython-notebook-networkx'),
    url("subplots/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='make_subplots'),
        name='ipython-notebook-make_subplots'),
    url("basemap-maps/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='basemap'),
        name='ipython-notebook-basemap'),
    url("collaboration/$",
        IPythonNotebookPage.as_view(
            lang='ipython-notebooks',
            notebook='collaborate'),
        name='ipython-notebook-collaborate')
)
